sudo: false
language: python
python: "2.7"
before_install:
# Decrypt the credentials we added to the repo using the key we added with the Travis command line tool
- openssl aes-256-cbc -K $encrypted_58e579ff8214_key -iv $encrypted_58e579ff8214_iv
  -in credentials.tar.gz.enc -out credentials.tar.gz -d
# If the SDK is not already cached, download it and unpack it
- tar -xzf credentials.tar.gz
- mkdir -p lib
env:
- SQLALCHEMY_DATABASE_URI=postgresql+psycopg2://postgres:swe-readers@/postgres?host=/cloudsql/cs373-idb:us-central1:idb
install:
# Install the Python dependencies
- pip install -r requirements.txt
script:
- python app/tests.py
- coverage run    --app/tests.py >  tests.tmp 2>&1
- coverage report -m                      >> tests.tmp
# [START travis_deploy]
deploy:
    provider: gae
    # Skip cleanup so api_key.py and vendored dependencies are still there
    skip_cleanup: true
    keyfile: client-secret.json
    project: cs373-idb
    default: true
    on:
        all_branches: true
# [END travis_deploy]